name: "kuka_lwr"

loadURDF:
  fileName: "{ik_ros_examples}/robots/kuka_lwr.urdf"
  useFixedBase: 1

object_tf:
  offset: [0.5, 0., 0.]

initial_joint_position:
  lwr_arm_0_joint: 0.0
  lwr_arm_1_joint: 30.0
  lwr_arm_2_joint: 0.0
  lwr_arm_3_joint: -90.0
  lwr_arm_4_joint: 0.0
  lwr_arm_5_joint: 60.0
  lwr_arm_6_joint: 0.0

is_visual_robot: false

setJointMotorControlArrayParameters:
  controlMode: "POSITION_CONTROL"

enabled_joint_force_torque_sensors: ["lwr_arm_6_joint"]

publish_joint_state_frequency: 30

broadcast_link_states: true
self.broadcast_link_states_hz: 50

start_ik_callback: true
